config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'questions#index'

  get 'about', to: 'static_pages#about'
  get 'term', to: 'static_pages#term'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create] do
    collection do
      get 'likes'
    end
  end
  resource :profile, only: %i[show edit update]

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'search'
      get 'organization_search'
      get 'like_rank'
      get 'my_posts'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :questions do
    collection do 
      get 'search'
      get 'my_questions'
    end
    get 'result', to: 'question_answers#result'
  end

  resources :chat_groups do
    get 'join', to: 'chat_groups#join'
    delete 'leave', to: 'chat_groups#leave'
    collection do
      get 'search'
      get 'my_chat_groups'
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/views/comments/_comment.html.erb
<tr>
  <td style="width: 60px">
    <%= image_tag comment.user.avatar_url, class: "rounded-full", size: '60x60' %>
  </td>
  <td>
    <h3><%= comment.user.name %></h3>
    <div>
      <p><%= comment.body %></p>
    <div>
  </td>

  <% if comment.user == current_user %>
    <td>
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to comment_path(comment), class: 'js-delete-comment-button', data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm') }, remote: true do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-12">
    <table class="table w-full", id="js-table-comment">
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-sm-12 mb-4">
    <%= form_with model: [post, comment], id: 'new_comment' do |f| %>
      <div class="text-center">
        <%= f.text_area :body, class: 'input input-accent w-7/12', row: 4, placeholder: Comment.human_attribute_name(:body), id: 'js-new-comment-body' %>
      </div>
      <div class="text-right pr-72">
        <%= f.submit t('defaults.comment'), class: 'btn btn-primary text-white font-bold' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
# 既に表示されているエラーメッセージがあった場合は削除する
$("#error_messages").remove()

# コメント作成処理の結果によって処理を分岐させる
<% if @comment.errors.present? %>
  # エラーがある、処理失敗時にはエラーメッセージのパーシャルを表示させる
  $("#new_comment").prepend("<%= j(render('shared/error_messages', object: @comment)) %>")

<% else %>
  # エラーがない、処理成功時には作成されたコメント内容をHTML要素として追加する
  $("#js-table-comment").prepend("<%= j(render('comments/comment', comment: @comment)) %>")

  # コメント入力フォームのテキストは表示する必要がないので、空文字に置き換えて内容をクリアする
  $("#js-new-comment-body").val('')
<% end %>

app/views/comments/destroy.js.erb
$("tr#comment-<%= @comment.id %>").remove()