config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'questions#index'

  get 'about', to: 'static_pages#about'
  get 'term', to: 'static_pages#term'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create] do
    collection do
      get 'likes'
    end
  end
  resource :profile, only: %i[show edit update]

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'search'
      get 'organization_search'
      get 'like_rank'
      get 'my_posts'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :questions do
    collection do 
      get 'search'
      get 'my_questions'
    end
    get 'result', to: 'question_answers#result'
  end

  resources :chat_groups do
    get 'join', to: 'chat_groups#join'
    delete 'leave', to: 'chat_groups#leave'
    collection do
      get 'search'
      get 'my_chat_groups'
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/chat_group.rb
class ChatGroup < ApplicationRecord
  has_many :chat_group_users, dependent: :destroy
  has_many :users, through: :chat_group_users, source: :user
  has_many :messages, dependent: :destroy
  belongs_to :organization, optional: true

  mount_uploader :image, ImageUploader

  validates :group_name, presence: true, length: { maximum: 255 }

  scope :group_name_contain, ->(word) { where('group_name LIKE ?', "%#{word}%") }
  scope :group_description_contain, ->(word) { where('chat_groups.group_description LIKE ?', "%#{word}%") }
  scope :with_organization, ->(organization_name) { joins(:organization).where(organizations: { name: organization_name }) }
end

app/controllers/chat_groups_controller.rb
class ChatGroupsController < ApplicationController
  before_action :ensure_correct_user, only: %i[edit update]

  def index
    chat_groups = if (organization_name = params[:organization_name])
                    ChatGroup.with_organization(organization_name)
                  else
                    ChatGroup.all
                  end
    @chat_groups = chat_groups.includes(:chat_group_users).order(created_at: :desc).page(params[:page])
    @organizations = Organization.all
    @organization_chat_groups = ChatGroup.includes(:organization).where(organization_id: params[:organization_id]).order(created_at: :desc).page(params[:page])
  end

  def new
    @chat_group = ChatGroup.new
  end

  def join
    @chat_group = ChatGroup.find(params[:chat_group_id])
    @chat_group.users << current_user
    redirect_to chat_group_path(@chat_group), success: t('defaults.join_chat_group')
  end

  def create
    @chat_group = current_user.chat_groups.build(chat_group_params)
    @chat_group.owner_id = current_user.id
    @chat_group.users << current_user
    if @chat_group.save
      redirect_to chat_groups_path, success: t('defaults.message.created', item: ChatGroup.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_created', item: ChatGroup.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @chat_group = ChatGroup.find(params[:id])
    @messages = @chat_group.messages
  end

  def edit; end

  def update
    if @chat_group.update(chat_group_params)
      redirect_to chat_groups_path, success: t('defaults.message.updated', item: ChatGroup.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_created', item: ChatGroup.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    delete_group = ChatGroup.find(params[:id])
    delete_group.destroy!
    redirect_to chat_groups_path, success: t('defaults.message.deleted', item: ChatGroup.model_name.human), status: :see_other
  end

  def leave
    @chat_group = ChatGroup.find(params[:chat_group_id])
    @chat_group.users.delete(current_user)
    redirect_to chat_groups_path, success: t('defaults.leave_chat_group')
  end

  def search
    @search_form = SearchChatGroupsForm.new(search_chat_group_params)
    @chat_groups = @search_form.search.includes(:chat_group_users).order(created_at: :desc).page(params[:page])
    @organizations = Organization.all
  end

  def my_chat_groups
    my_chat_groups = ChatGroup.where(owner_id: current_user.id).order("created_at DESC")
    @my_chat_groups = Kaminari.paginate_array(my_chat_groups).page(params[:page])
  end

  private

  def chat_group_params
    params.require(:chat_group).permit(:group_name, :group_description, :image, :image_cache, :organization_id)
  end

  def ensure_correct_user
    @chat_group = ChatGroup.find(params[:id])
    unless @chat_group.owner_id == current_user.id
      redirect_to chat_groups_path, error: t('defaults.not_creator')
    end
  end

  def search_chat_group_params
    params.fetch(:q, {}).permit(:group_name_or_group_description)
  end
end

app/views/chat_groups/_chat_group.html.erb
<div class="p-6">
  <div class="card card-compact hover:bg-stone-100 rounded-lg shadow-lg mb-2 sm:mb-4">
    <% if chat_group.image.present? %>
      <%= link_to image_tag(chat_group.image.url), chat_group_path(chat_group.id) %>
    <% end %>
    <%= render partial: 'organizations/chat_group_organization', locals: { chat_group: chat_group } %>
      <div class="text-accent md:text-xl font-bold md:m-auto">
        <div class="flex justify-center hover:text-blue-500">
          <%= link_to chat_group.group_name, chat_group_path(chat_group.id) %>(<%= link_to chat_group.users.count, chat_group_path(chat_group.id) %>)
        </div>
        <div class="pt-4 text-center text-secondary hover:text-red-500 md:text-xl font-bold md:m-auto">
          <%= link_to chat_group.group_description, chat_group_path(chat_group.id) %>
        </div>
      </div>
  </div>
</div>

app/views/chat_groups/_form.html.erb
<%= form_with model: @chat_group, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-control mb-10">
    <%= f.label :organization, class: 'font-bold' %>
    <%= f.select :organization_id, Organization.pluck(:name, :id), {include_blank: true}, {data: { controller: 'slim', slim_target: 'field' } } %>
  </div>
  <div class="form-control mb-10">
    <%= f.label :group_name, class: 'font-bold' %>
    <%= f.text_field :group_name, class: 'input input-accent' %>
  </div>
  <div class="form-control mb-10">
    <%= f.label :group_description, class: 'font-bold' %>
    <%= f.text_area :group_description, class: 'input input-accent' %>
  </div>
  <div class="form-control mb-10">
    <%= f.label :image, class: 'font-bold' %>
    <%= f.file_field :image, onchange: 'imagePreview(event)', accept: 'image/*', class: 'file-input file-input-bordered file-input-accent w-full max-w-xs' %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-control mb-10">
    <div id="preview"></div>
  </div>
  <p class="text-sm text-end">*必須項目</p>
  <%= f.submit class: 'btn btn-block btn-secondary mt-10 mb-20 lg:mb-10' %>
<% end %>

<script>
function imagePreview(event) {
    const file = event.target.files[0];
    const reader = new FileReader();
    const preview = document.getElementById("preview");
    const previewImage = document.getElementById("previewImage");

    if (previewImage != null) {
        preview.removeChild(previewImage);
    }
    reader.onload = function() {
        const image = document.createElement("img");
        image.setAttribute("src", reader.result);
        image.setAttribute("id", "previewImage");
        preview.appendChild(image);
    };
    reader.readAsDataURL(file);
}
</script>

app/views/chat_groups/_organization_chat_group.html.erb
<% if @organization_chat_groups.present? %>
  <% @organization_chat_groups.each do |chat_group| %>
    <div class="p-6">
      <div class="card card-compact hover:bg-stone-100 rounded-lg shadow-lg mb-2 sm:mb-4">
        <% if chat_group.image.present? %>
          <%= link_to image_tag(chat_group.image.url), chat_group_path(chat_group.id) %>
        <% end %>
        <%= render partial: 'organizations/chat_group_organization', locals: { chat_group: chat_group } %>
        <%= link_to chat_group_path(chat_group.id) do %>
          <div class="text-accent md:text-xl font-bold md:m-auto">
            <div class="flex justify-center">
              <%= chat_group.group_name %>(<%= chat_group.users.count %>)
            </div>
            <div class="pt-4 text-center text-secondary hover:text-blue-500 md:text-xl font-bold md:m-auto">
              <%= chat_group.group_description %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <h1 class="text-md lg:text-2xl font-bold text-center md:mb-6"><%= (t 'defaults.no_organization')%></h1>
<% end %>

app/views/chat_groups/_search_chat_group_form.html.erb
<div class="py-6 md:py-8">
  <div class="mb-2 text-sm font-medium" >
    <div class="relative mx-auto w-full md:w-2/3">
      <%= form_with model: search_form, url: search_chat_groups_path, scope: :q, method: :get do |f| %>
       <div class="flex flex-row">
        <%= f.search_field :group_name_or_group_description, class: 'input input-accent w-full p-4 pl-10 text-sm border border-red-500 rounded-lg', placeholder: (t 'defaults.name_or_description') %>
        <div class="text-right flex flex-row">
          <i class="fa-solid fa-magnifying-glass btn btn-secondary">
            <%= f.submit (t 'defaults.search'), class: 'p-4' %>
          </i>
        </div>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chat_groups/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <h2 class="text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-8 md:text-red-500 animate-text-shadow-drop-center">
      <%= t '.title' %>
    </h2>
    <div class="max-w-xl border rounded-xl mx-auto">
      <div class="flex flex-col bg-stone-50 gap-4 p-4 md:p-8">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/chat_groups/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 md:py-8">
  <div class="max-w-screen-xl px-6 md:px-10 mx-auto">
    <div class="mb-10 md:mb-16">
      <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center">
        <%= t '.title' %>
      </h2>
    </div>
    <div class="m-8">
      <%= render 'search_chat_group_form', search_form: @search_form %>
    </div>
    <p class="text-center text-green-500 font-bold text-2xl">団体一覧</p>
    <div class="pt-5">
      <% @organizations.each do |organization| %>
        <div class="badge bg-primary rounded-none font-bold">
          <%= organization.name %>
        </div>
      <% end %>
    </div>
    <div class="pt-5">
      <%= form_tag(chat_groups_path, method: "get") do %>
        <%= select_tag :organization_id, options_from_collection_for_select(@organizations, "id", "name", params[:organization_id]), prompt: "団体を選択してください", class: "form-control" %>
        <div class="pl-28 pb-16">
          <%= submit_tag "絞り込み", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
    <% if params[:organization_id] %>
      <%= render partial: 'chat_groups/organization_chat_group', locals: { chat_group: @chat_group } %>
    <% else %>
      <%= render @chat_groups %>
    <% end %>
    </div>
    <div>
      <%= paginate @chat_groups %>
      <%= paginate @organization_chat_groups %>
    </div>
  </div>
</div>

app/views/chat_groups/my_chat_groups.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 md:py-8">
  <div class="max-w-screen-xl px-6 md:px-10 mx-auto">
    <div class="mb-10 md:mb-16">
      <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center">
        <%= t '.title' %>
      </h2>
    </div>
      <% if @my_chat_groups.present? %>
        <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
          <%= render @my_chat_groups %>
          <%= paginate @my_chat_groups %>
        </div>
      <% else %>
        <h1 class="text-md lg:text-2xl font-bold text-center md:mb-6"><%= t '.no_result' %></h1>
      <% end %>
  </div>
</div>

app/views/chat_groups/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <h2 class="text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-8 md:text-red-500 animate-text-shadow-drop-center">
      <%= t '.title' %>
    </h2>
    <div class="max-w-xl border rounded-xl mx-auto">
      <div class="flex flex-col bg-stone-50 gap-4 p-4 md:p-8">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/chat_groups/search.html.erb
<% content_for(:title, t('.search_result')) %>
<div class="py-6 md:py-8">
  <div class="max-w-screen-xl px-6 md:px-10 mx-auto">
    <div class="mb-10 md:mb-16">
      <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center animate-text-shadow-drop-center">
        <%= t '.title' %>
      </h2>
    </div>
    <div class="m-8">
      <%= render 'search_chat_group_form', search_form: @search_form %>
    </div>
    <p class="text-center text-green-500 font-bold text-2xl">団体一覧</p>
    <div class="pt-5">
      <% @organizations.each do |organization| %>
        <div class="badge bg-primary rounded-none font-bold">
          <%= organization.name %>
        </div>
      <% end %>
    </div>
    <% if @chat_groups.present? %>
      <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
        <%= render @chat_groups %>
      </div>
      <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
        <%= paginate @chat_groups %>
      </div>
    <% else %>
      <h1 class="text-md lg:text-2xl font-bold text-center md:mb-6"><%= t '.no_result' %></h1>
    <% end %>
  </div>
</div>

app/views/chat_groups/show.html.erb
<% content_for(:title, @chat_group.group_name) %>
<div class="navbar bg-slate-600 text-accent-content">
  <div class="navbar-start font-bold text-2xl">
    <h1 class="font-bold text-3xl flex flex-wrap"><%= link_to "＜チャット一覧", chat_groups_path %></h1>
  </div>
  <div class="navbar-end font-bold text-3xl flex justify-center mr-24">
    <%= @chat_group.group_name %>
  </div>
  <div class="navbar-end font-bold text-3xl space-x-6">
    <% if @chat_group.owner_id == current_user.id %>
      <%= link_to t('.edit'), edit_chat_group_path(@chat_group) %>
      <%= link_to t('.delete'), chat_group_path(@chat_group), data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm') } %>
    <% end %>
    <% if @chat_group.users.include?(current_user) %>
      <%= link_to t('.leave'), chat_group_leave_path(@chat_group), data: { turbo_method: :delete, turbo_confirm: t('.leave?') } %>
    <% else %>
      <%= link_to t('.join'), chat_group_join_path(@chat_group) %>
    <% end %>
  </div>
</div>

<%#ここの data-chat_group_id を使ってjs側で部屋を見分ける %>
<div id="messages" data-chat_group_id="<%= @chat_group.id %>">
  <% if @messages.present? %>
    <div class="pt-10">
      <%= render @messages %>
    </div>
  <% else %>
    <h2 class="font-bold text-center text-5xl m-40">チャットがまだありません...</h2>
  <% end %>
</div>

<% if @chat_group.users.include?(current_user) %>
    <div class="border-t-2 border-gray-200 px-4 pt-4 mb-2 sm:mb-0">
      <div class="relative flex">
        <div class="w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 placeholder-gray-600 pl-12 bg-gray-200 rounded-md py-3">
        <form>
          <input type="text" data-behavior="chat_group_speaker" placeholder="Enterで送信してください（チャットする場合はPCからお願いいたします）" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
          <input id="chat_group_id" type="hidden" name="chat_group_id" value="<%= @chat_group.id %>">
        </form>
        </div>
      </div>
    </div>
<% end %>