config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'questions#index'

  get 'about', to: 'static_pages#about'
  get 'term', to: 'static_pages#term'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create] do
    collection do
      get 'likes'
    end
  end
  resource :profile, only: %i[show edit update]

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'search'
      get 'organization_search'
      get 'like_rank'
      get 'my_posts'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :questions do
    collection do 
      get 'search'
      get 'my_questions'
    end
    get 'result', to: 'question_answers#result'
  end

  resources :chat_groups do
    get 'join', to: 'chat_groups#join'
    delete 'leave', to: 'chat_groups#leave'
    collection do
      get 'search'
      get 'my_chat_groups'
    end
  end
  mount ActionCable.server => '/cable'
end

app/views/shared/_before_login_header.erb
<header>
  <div class="navbar bg-accent text-accent-content">
    <div class="navbar-start">
      <%= link_to "Prowrest Numarasu", "#", class: "btn btn-accent" %>
    </div>
    <div class="navbar-end">
      <%= link_to "ログイン", "#", class: "btn btn-accent" %>
      <%= link_to "新規登録", "#", class: "btn btn-accent" %>
    </div>
  </div>
</header>

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-accent text-accent-content">
    <div class="navbar-start font-bold text-2xl">
      <%= link_to t('defaults.prowrest-numarasu'), about_path %>
    </div>
    <div class="navbar-end space-x-6 font-bold">
      <%= link_to t('defaults.about'), about_path %>
      <%= link_to t('defaults.question_index'), questions_path %>
      <%= link_to t('defaults.index'), posts_path %>
      <%= link_to t('defaults.login'), login_path %>
      <%= link_to t('defaults.register'), new_user_path %>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'info' %>
    <div class="alert alert-info shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
        <span><%= message %></span>
      </div>
    </div>
  <% elsif message_type == 'success' %>
    <div class="alert alert-success shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span><%= message %></span>
      </div>
    </div>
  <% elsif message_type == 'error' %>
    <div class="alert alert-error shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span><%= message %></span>
      </div>
    </div>
  <% end %>  
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-blue-400">
  <div>
    <ul class="flex space-x-10 font-medium text-lg ">
      <li><%= link_to (t 'defaults.terms_of_use'), term_path %></li>
      <li><%= link_to (t 'defaults.privacy_policy'), privacy_path %></li>
      <li><%= link_to (t 'defaults.contact'), "https://forms.gle/Wgpy9Nd81KDU147H7" %></li>
    </ul>
    <div class="text-center">
      © 2023 プロレスヌマラス. All rights reserved.
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-accent text-accent-content">
    <div class="navbar-start font-bold text-2xl">
      <%= link_to t('defaults.prowrest-numarasu'), about_path %>
    </div>
    <div class="navbar-end">
      <div class="font-bold space-x-6">
      <div class="dropdown dropdown-hover dropdown-end">
        <div>
          <%= link_to t('defaults.about'), about_path %>
        </div>
      </div>
        <div class="dropdown dropdown-hover dropdown-end">
          <div>
            <%= link_to t('defaults.question_index'), questions_path %>
          </div>
          <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
            <li>
              <%= link_to t('defaults.question_new'), new_question_path, class: "btn btn-accent" %>
            </li>
          </ul>
        </div>
        <div class="dropdown dropdown-hover dropdown-end">
          <div>
            <%= link_to t('defaults.index'), posts_path %>
          </div>
          <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
            <li>
              <%= link_to t('defaults.new'), new_post_path, class: "btn btn-accent" %>
            </li>
          </ul>
        </div>
        <div class="dropdown dropdown-hover dropdown-end">
          <div>
            <%= link_to t('defaults.chat_group_index'), chat_groups_path %>
          </div>
          <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
            <li>
              <%= link_to t('defaults.chat_group_new'), new_chat_group_path, class: "btn btn-accent" %>
            </li>
          </ul>
        </div>
      </div>
      <div class="dropdown dropdown-hover dropdown-end">
        <div class="btn btn-ghost normal-case rounded-full">
          <%= image_tag current_user.avatar_url, size: '50x50', class: "rounded-full" %>
        </div>
        <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <%= link_to current_user.name, profile_path, class: "btn btn-secondary" %>
          </li>
          <li>
            <%= link_to t('defaults.logout'), logout_path, data: { turbo_method: :delete, turbo_confirm: t('defaults.message.logout_confirm') }, class: "btn btn-accent" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>