config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'questions#index'

  get 'about', to: 'static_pages#about'
  get 'term', to: 'static_pages#term'
  get 'privacy', to: 'static_pages#privacy'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create] do
    collection do
      get 'likes'
    end
  end
  resource :profile, only: %i[show edit update]

  resources :posts do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'search'
      get 'organization_search'
      get 'like_rank'
      get 'my_posts'
    end
  end

  resources :likes, only: %i[create destroy]
  resources :questions do
    collection do 
      get 'search'
      get 'my_questions'
    end
    get 'result', to: 'question_answers#result'
  end

  resources :chat_groups do
    get 'join', to: 'chat_groups#join'
    delete 'leave', to: 'chat_groups#leave'
    collection do
      get 'search'
      get 'my_chat_groups'
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/post.rb
class Post < ApplicationRecord
  before_save :slugify

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  belongs_to :organization, optional: true

  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, length: { maximum: 65_535 }

  scope :with_tag, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }
  scope :title_contain, ->(word) { where('title LIKE ?', "%#{word}%") }
  scope :body_contain, ->(word) { where('posts.body LIKE ?', "%#{word}%") }
  scope :with_organization, ->(organization_name) { joins(:organization).where(organizations: { name: organization_name }) }

  # YouTubeURLを更新する際に、削ぎ落とす前のリンクURLがDBに保存されてしまうため、URLを削ぎ落とす
  def slugify
    self.url = url.last(11)
  end

  def liked_by?(user)
    liking_users.include?(user)
  end

  def save_with_tags(tag_names:)
    ActiveRecord::Base.transaction do
      self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name.strip) }
      save!
    end
    true
  rescue StandardError
    false
  end

  def tag_names
    # NOTE: pluckだと新規作成失敗時に値が残らない(返り値がnilになる)
    tags.map(&:name).join(',')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: %i[index show search like_rank]
  before_action :set_post, only: %i[edit update destroy]

  def index
    posts = if (tag_name = params[:tag_name])
              Post.with_tag(tag_name)
            elsif (organization_name = params[:organization_name])
              Post.with_organization(organization_name)
            else
              Post.all
            end
    @posts = posts.includes(:user).order(created_at: :desc).page(params[:page])
    @organizations = Organization.all
    @organization_posts = Post.includes(:organization).where(organization_id: params[:organization_id]).order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save_with_tags(tag_names: params.dig(:post, :tag_names).split(',').uniq)
      redirect_to posts_path, success: t('defaults.message.created', item: Post.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_created', item: Post.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def edit
    @tag_list = @post.tags.pluck(:name).join(',')
  end

  def update
    @post.assign_attributes(post_params)
    if @post.save_with_tags(tag_names: params.dig(:post, :tag_names).split(',').uniq)
      redirect_to post_path(@post), success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now[:error] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, success: t('defaults.message.deleted', item: Post.model_name.human), status: :see_other
  end

  def search
    @search_form = SearchPostsForm.new(search_post_params)
    @posts = @search_form.search.includes(:user).order(created_at: :desc).page(params[:page])
    @organizations = Organization.all
  end

  def like_rank
    posts = Post.includes(:liking_users).sort{|a,b| b.liking_users.size <=> a.liking_users.size}
    @posts = Kaminari.paginate_array(posts).page(params[:page])
  end

  def my_posts
    my_posts = Post.where(user_id: current_user.id).includes(:user).order("created_at DESC")
    @my_posts = Kaminari.paginate_array(my_posts).page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:image, :image_cache, :url, :title, :body, :organization_id)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def search_post_params
    params.fetch(:q, {}).permit(:title_or_body, :tag_name)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-control mb-10">
    <%= f.label :organization, class: 'font-bold' %>
    <%= f.select :organization_id, Organization.pluck(:name, :id), {include_blank: true}, {data: { controller: 'slim', slim_target: 'field' } } %>
  </div>
  <div class="form-control mb-10">
    <%= f.label :title, class: 'font-bold' %>
    <%= f.text_field :title, class: 'input input-accent' %>
  </div>
  <div class="form-control mb-10">
    <%= f.label :body, class: 'font-bold' %>
    <%= f.text_area :body, class: 'input input-accent' %>
  </div>
  <div class="form-control mb-10">
    <%= f.label :image, class: 'font-bold' %>
    <%= f.file_field :image, onchange: 'imagePreview(event)', accept: 'image/*', class: 'file-input file-input-bordered file-input-accent w-full max-w-xs' %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="form-control mb-10">
    <div id="preview"></div>
  </div>
  <div class="form-control mb-10">
    <%= f.label :url, class: 'font-bold' %>
    <%= f.text_field :url, class: 'input input-accent', placeholder: (t 'defaults.url') %>
  </div>
  <div class="form-control mb-10">
    <%= f.label :tag_names, class: 'font-bold' %>
    <%= f.text_field :tag_names, class: 'input input-accent', value: @tag_list, placeholder: (t 'defaults.tag_form') %>
  </div>
  <p class="text-sm text-end">*必須項目</p>
  <%= f.submit class: 'btn btn-block btn-secondary mt-10 mb-20 lg:mb-10'%>
<% end %>

<script>
function imagePreview(event) {
    const file = event.target.files[0];
    const reader = new FileReader();
    const preview = document.getElementById("preview");
    const previewImage = document.getElementById("previewImage");

    if (previewImage != null) {
        preview.removeChild(previewImage);
    }
    reader.onload = function() {
        const image = document.createElement("img");
        image.setAttribute("src", reader.result);
        image.setAttribute("id", "previewImage");
        preview.appendChild(image);
    };
    reader.readAsDataURL(file);
}
</script>

app/views/posts/_organization_post.html.erb
<% if @organization_posts.present? %>
  <% @organization_posts.each do |post| %>
    <div class="p-6">
    <div class="card card-compact hover:bg-stone-100 rounded-lg shadow-lg mb-2 sm:mb-4">
      <% if post.image.present? %>
        <%= link_to image_tag(post.image.url), post_path(post), class: 'w-full h-full object-cover object-center' %>
      <% end %>
      <% if post.url.present? %>
        <iframe width="300" height="300" src="https://www.youtube.com/embed/<%= post.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end %>
      <%= render partial: 'organizations/post_organization', locals: { post: post } %>
      <%= link_to post.title, post_path(post), class: 'text-accent hover:text-blue-500 md:text-xl font-bold md:m-auto' %>
      <div class="text-right mr-12">
        <%= render 'actions/like_button', { post: post } %>
      </div>
      <div class="pt-4 space-x-3">
        <%= render post.tags %>
      </div>
    </div>
  </div>
  <% end %>
<% else %>
  <h1 class="text-md lg:text-2xl font-bold text-center md:mb-6"><%= (t 'defaults.no_organization')%></h1>
<% end %>
  

app/views/posts/_post.html.erb
<div class="p-6">
  <div class="card card-compact hover:bg-stone-100 rounded-lg shadow-lg mb-2 sm:mb-4 border-red-500">
    <% if post.image.present? %>
      <%= link_to image_tag(post.image.url), post_path(post), class: 'w-full h-full object-cover object-center' %>
    <% end %>
    <% if post.url.present? %>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/<%= post.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %>
    <%= render partial: 'organizations/post_organization', locals: { post: post } %>
    <%= link_to post.title, post_path(post), class: 'text-accent hover:text-blue-500 md:text-xl font-bold md:m-auto' %>
    <div class="text-right mr-6">
      <%= render 'actions/like_button', { post: post } %>
      <%= link_to post_path(post) do %>
        <i class="fa-regular fa-comment fa-2x"></i>
        <%= post.comments.count %>
      <% end %>
    </div>
    <div class="pt-4 space-x-3">
      <%= render post.tags %>
    </div>
  </div>
</div>

app/views/posts/_search_post_form.html.erb
<div class="py-6 md:py-8">
  <div class="mb-2 text-sm font-medium" >
    <div class="relative mx-auto w-full md:w-2/3">
      <%= form_with model: search_form, url: search_posts_path, scope: :q, method: :get do |f| %>
       <div class="flex flex-row">
        <%= f.search_field :title_or_body, class: 'input input-accent w-full p-4 pl-10 text-sm border border-red-500 rounded-lg', placeholder: (t 'defaults.title_or_body') %>
        <div class="text-right flex flex-row">
          <i class="fa-solid fa-magnifying-glass btn btn-secondary">
            <%= f.submit (t 'defaults.search'), class: 'p-4' %>
          </i>
        </div>
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <h2 class="text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-8 md:text-red-500 animate-text-shadow-drop-center">
      <%= t '.title' %>
    </h2>
    <div class="max-w-xl border rounded-xl mx-auto">
      <div class="flex flex-col bg-stone-50 gap-4 p-4 md:p-8 ">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 md:py-8">
  <div class="max-w-screen-xl px-6 md:px-10 mx-auto">
    <div class="mb-10 md:mb-16">
      <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center">
        <%= t '.title' %>
      </h2>
    </div>
    <div class="m-8">
      <%= render 'search_post_form', search_form: @search_form %>
    </div>
    <p class="text-center text-green-500 font-bold text-2xl">団体一覧</p>
      <div class="pt-5">
        <% @organizations.each do |organization| %>
          <div class="badge bg-primary rounded-none font-bold">
            <%= organization.name %>
          </div>
        <% end %>
      </div>
    <div class="pt-5">
      <%= form_tag(posts_path, method: "get") do %>
        <%= select_tag :organization_id, options_from_collection_for_select(@organizations, "id", "name", params[:organization_id]), prompt: "団体を選択してください", class: "form-control" %>
        <div class="pl-28 pb-16">
          <%= submit_tag "絞り込み", class: "btn btn-primary" %>
          <div class="flex flex-row-reverse">
            <div class="flex space-x-6">
              <% if current_user.present? %>
                <button><%= link_to t('defaults.likes'), likes_users_path, class: "btn btn-secondary" %>
              <% end %>
              <button><%= link_to t('.like_rank'), like_rank_posts_path, class: "btn btn-accent font-bold" %></button>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
     <% if params[:organization_id] %>
      <%= render partial: 'posts/organization_post', locals: { post: @post } %>
     <% else %>
      <%= render @posts %>
     <% end %>
    </div>
    <div>
      <%= paginate @posts %>
      <%= paginate @organization_posts %>
    </div>
  </div>
</div>

app/views/posts/like_rank.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 md:py-8">
  <div class="max-w-screen-xl px-6 md:px-10 mx-auto">
    <div class="mb-10 md:mb-16">
      <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center">
        <%= t '.title' %>
      </h2>
    </div>
      <% if @posts.present? %>
        <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
          <%= render @posts %>
          <%= paginate @posts %>
        </div>
      <% else %>
        <h1 class="text-md lg:text-2xl font-bold text-center md:mb-6"><%= t '.no_result' %></h1>
      <% end %>
  </div>
</div>

app/views/posts/my_posts.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 md:py-8">
  <div class="max-w-screen-xl px-6 md:px-10 mx-auto">
    <div class="mb-10 md:mb-16">
      <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center">
        <%= t '.title' %>
      </h2>
    </div>
      <% if @my_posts.present? %>
        <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
          <%= render @my_posts %>
          <%= paginate @my_posts %>
        </div>
      <% else %>
        <h1 class="text-md lg:text-2xl font-bold text-center md:mb-6"><%= t '.no_result' %></h1>
      <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="py-6 sm:py-8 lg:py-12">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <h2 class="text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-8 md:text-red-500 animate-text-shadow-drop-center">
      <%= t '.title' %>
    </h2>
    <div class="max-w-xl border rounded-xl mx-auto">
      <div class="flex flex-col bg-stone-50 gap-4 p-4 md:p-8">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<% content_for(:title, t('.search_result')) %>
<div class="py-6 md:py-8">
  <div class="max-w-screen-xl px-6 md:px-10 mx-auto">
    <div class="mb-10 md:mb-16">
      <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center">
        <%= t '.title' %>
      </h2>
    </div>
    <div class="m-8">
      <%= render 'search_post_form', search_form: @search_form %>
    </div>
    <p class="text-center text-green-500 font-bold text-2xl">団体一覧</p>
    <div class="pt-5">
      <% @organizations.each do |organization| %>
        <div class="badge bg-primary rounded-none font-bold">
          <%= organization.name %>
        </div>
      <% end %>
    </div>
    <% if @posts.present? %>
      <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
        <%= render @posts %>
      </div>
      <div class="grid grid-cols-2 mb-20 md:mb-10 md:grid-cols-3 gap-x-4 lg:gap-x-8 gap-y-8 lg:gap-y-12 bg-stone-50">
        <%= paginate @posts %>
      </div>
    <% else %>
      <h1 class="text-md lg:text-2xl font-bold text-center md:mb-6"><%= t '.no_result' %></h1>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>
<div class="bg-stone-100 p-4 m-4">
  <%= link_to "＜投稿一覧", posts_path, class: 'font-bold text-2xl text-blue-500' %>
  <h2 class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl animate-text-shadow-drop-center"><%= t '.title' %></h2>
  <div class="py-6 sm:py-8 lg:py-12">
    <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
      <div class="card max-w-xl border rounded-xl mx-auto">
        <% if @post.image.present? && @post.url.present? %>
          <%= image_tag @post.image_url %>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% elsif @post.image.present? %>
          <%= image_tag @post.image_url %>
        <% elsif @post.url.present? %>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
        <div class="card-body text-accent-content">
          <h2 class="text-accent md:text-3xl font-bold md:m-auto"><%= @post.title %></h2>
          <div class="text-accent md:text-xl font-bold md:flex">
            <%= image_tag @post.user.avatar_url, size: '30x30', class: "rounded-full" %>
            <%= @post.user.name %>
          </div>
          <p class="text-blue-500 md:text-xl font-bold md:pt-5"><%= @post.body %></p>
          <div class="pt-20 space-x-5">
            <%= render @post.tags %>
          </div>
          <p class="flex justify-end mb-4 text-accent text-accent-focus md:text-lg font-bold"><%= I18n.l(@post.created_at, format: :long) %></p>
          <div class="flex gap-8 justify-end">
            <%= render 'actions/like_button', { post: @post } %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center space-x-32">
    <% if @post.user == current_user %>
      <button class="btn btn-secondary md:text-xl"><%= link_to (t 'defaults.edit'), edit_post_path %></button>
      <button class="btn btn-accent md:text-xl"><%= link_to (t 'defaults.delete'), post_path(@post), data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm') } %></button>
    <% end %>
  </div>
  <% if @comment.user = current_user %>
    <div class="text-accent-content text-2xl lg:text-3xl font-bold text-center text-red-500 text-5xl md:pt-12">
      <%= t '.comment' %>
    </div>
    <div class="pt-12">
     <%= render 'comments/form', { post: @post, comment: @comment } %>
    </div>
  <% end %>
    <%= render 'comments/comments', { comments: @comments } %>
</div>